// RUN: mlir-opt -restructure-clift %s | FileCheck %s -check-prefix=CHECK-RESTRUCTURE

module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<"dlti.endianness", "little">, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>>} {
  llvm.mlir.global private unnamed_addr constant @".str"("%d\00") {addr_space = 0 : i32, alignment = 1 : i64, dso_local}
  llvm.func @foo(%arg0: i32, %arg1: i32) attributes {passthrough = ["noinline", "nounwind", "optnone", ["uwtable", "2"], ["frame-pointer", "all"], ["min-legal-vector-width", "0"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]} {
    %0 = llvm.mlir.constant(1 : i32) : i32
    %1 = llvm.mlir.constant(10 : i32) : i32
    %2 = llvm.mlir.constant(5 : i32) : i32
    %3 = llvm.mlir.constant("%d\00") : !llvm.array<3 x i8>
    %4 = llvm.mlir.addressof @".str" : !llvm.ptr
    %5 = llvm.mlir.constant(7 : i32) : i32
    %6 = llvm.alloca %0 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
    %7 = llvm.alloca %0 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
    llvm.store %arg0, %6 : i32, !llvm.ptr
    llvm.store %arg1, %7 : i32, !llvm.ptr
    llvm.br ^bb1
  ^bb1:  // 2 preds: ^bb0, ^bb8
    %8 = llvm.load %6 : !llvm.ptr -> i32
    %9 = llvm.icmp "slt" %8, %1 : i32
    llvm.cond_br %9, ^bb2, ^bb9
  ^bb2:  // pred: ^bb1
    llvm.br ^bb3
  ^bb3:  // 2 preds: ^bb2, ^bb6
    %10 = llvm.load %6 : !llvm.ptr -> i32
    %11 = llvm.icmp "eq" %10, %2 : i32
    llvm.cond_br %11, ^bb4, ^bb5
  ^bb4:  // pred: ^bb3
    %12 = llvm.load %6 : !llvm.ptr -> i32
    %13 = llvm.call @printf(%4, %12) : (!llvm.ptr, i32) -> i32
    llvm.br ^bb8
  ^bb5:  // pred: ^bb3
    %14 = llvm.load %7 : !llvm.ptr -> i32
    %15 = llvm.call @printf(%4, %14) : (!llvm.ptr, i32) -> i32
    %16 = llvm.load %7 : !llvm.ptr -> i32
    %17 = llvm.icmp "eq" %16, %5 : i32
    llvm.cond_br %17, ^bb6, ^bb7
  ^bb6:  // pred: ^bb5
    llvm.br ^bb3
  ^bb7:  // pred: ^bb5
    llvm.br ^bb8
  ^bb8:  // 2 preds: ^bb4, ^bb7
    %18 = llvm.load %6 : !llvm.ptr -> i32
    %19 = llvm.add %18, %0  : i32
    llvm.store %19, %6 : i32, !llvm.ptr
    %20 = llvm.load %7 : !llvm.ptr -> i32
    %21 = llvm.add %20, %0  : i32
    llvm.store %21, %7 : i32, !llvm.ptr
    llvm.br ^bb1
  ^bb9:  // pred: ^bb1
    llvm.return
  }
  llvm.func @printf(!llvm.ptr, ...) -> i32 attributes {passthrough = [["frame-pointer", "all"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]}
}

// CHECK-RESTRUCTURE-LABEL: module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<"dlti.endianness", "little">, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>>} {
// CHECK-RESTRUCTURE-NEXT: llvm.mlir.global private unnamed_addr constant @".str"("%d\00") {addr_space = 0 : i32, alignment = 1 : i64, dso_local}
// CHECK-RESTRUCTURE-NEXT: llvm.func @foo(%arg0: i32, %arg1: i32) attributes {passthrough = ["noinline", "nounwind", "optnone", ["uwtable", "2"], ["frame-pointer", "all"], ["min-legal-vector-width", "0"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]} {
// CHECK-RESTRUCTURE-NEXT:     %0 = clift.make_label !clift.label
// CHECK-RESTRUCTURE-NEXT:     %1 = clift.make_label !clift.label
// CHECK-RESTRUCTURE-NEXT:     %2 = clift.make_label !clift.label
// CHECK-RESTRUCTURE-NEXT:     %3 = llvm.mlir.constant(1 : i32) : i32
// CHECK-RESTRUCTURE-NEXT:     %4 = llvm.mlir.constant(10 : i32) : i32
// CHECK-RESTRUCTURE-NEXT:     %5 = llvm.mlir.constant(5 : i32) : i32
// CHECK-RESTRUCTURE-NEXT:     %6 = llvm.mlir.constant("%d\00") : !llvm.array<3 x i8>
// CHECK-RESTRUCTURE-NEXT:     %7 = llvm.mlir.addressof @".str" : !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:     %8 = llvm.mlir.constant(7 : i32) : i32
// CHECK-RESTRUCTURE-NEXT:     %9 = llvm.alloca %3 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:     %10 = llvm.alloca %3 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:     llvm.store %arg0, %9 : i32, !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:     llvm.store %arg1, %10 : i32, !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:     llvm.br ^bb2
// CHECK-RESTRUCTURE-NEXT:   ^bb1:  // pred: ^bb2
// CHECK-RESTRUCTURE-NEXT:     clift.assign_label %0 !clift.label
// CHECK-RESTRUCTURE-NEXT:     llvm.return
// CHECK-RESTRUCTURE-NEXT:   ^bb2:  // pred: ^bb0
// CHECK-RESTRUCTURE-NEXT:     clift.loop {
// CHECK-RESTRUCTURE-NEXT:       llvm.br ^bb1
// CHECK-RESTRUCTURE-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-RESTRUCTURE-NEXT:       %11 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:       %12 = llvm.icmp "slt" %11, %4 : i32
// CHECK-RESTRUCTURE-NEXT:       llvm.cond_br %12, ^bb5, ^bb7
// CHECK-RESTRUCTURE-NEXT:     ^bb2:  // pred: ^bb5
// CHECK-RESTRUCTURE-NEXT:       clift.loop {
// CHECK-RESTRUCTURE-NEXT:         llvm.br ^bb1
// CHECK-RESTRUCTURE-NEXT:       ^bb1:  // pred: ^bb0
// CHECK-RESTRUCTURE-NEXT:         %19 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:         %20 = llvm.icmp "eq" %19, %5 : i32
// CHECK-RESTRUCTURE-NEXT:         llvm.cond_br %20, ^bb4, ^bb2
// CHECK-RESTRUCTURE-NEXT:       ^bb2:  // pred: ^bb1
// CHECK-RESTRUCTURE-NEXT:         %21 = llvm.load %10 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:         %22 = llvm.call @printf(%7, %21) : (!llvm.ptr, i32) -> i32
// CHECK-RESTRUCTURE-NEXT:         %23 = llvm.load %10 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:         %24 = llvm.icmp "eq" %23, %8 : i32
// CHECK-RESTRUCTURE-NEXT:         llvm.cond_br %24, ^bb3, ^bb5
// CHECK-RESTRUCTURE-NEXT:       ^bb3:  // pred: ^bb2
// CHECK-RESTRUCTURE-NEXT:         llvm.br ^bb6
// CHECK-RESTRUCTURE-NEXT:       ^bb4:  // pred: ^bb1
// CHECK-RESTRUCTURE-NEXT:         clift.goto %2 !clift.label
// CHECK-RESTRUCTURE-NEXT:       ^bb5:  // pred: ^bb2
// CHECK-RESTRUCTURE-NEXT:         clift.goto %1 !clift.label
// CHECK-RESTRUCTURE-NEXT:       ^bb6:  // pred: ^bb3
// CHECK-RESTRUCTURE-NEXT:         "clift.continue"() : () -> ()
// CHECK-RESTRUCTURE-NEXT:       } ^bb4, ^bb3
// CHECK-RESTRUCTURE-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-RESTRUCTURE-NEXT:       clift.assign_label %1 !clift.label
// CHECK-RESTRUCTURE-NEXT:       llvm.br ^bb6
// CHECK-RESTRUCTURE-NEXT:     ^bb4:  // pred: ^bb2
// CHECK-RESTRUCTURE-NEXT:       clift.assign_label %2 !clift.label
// CHECK-RESTRUCTURE-NEXT:       %13 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:       %14 = llvm.call @printf(%7, %13) : (!llvm.ptr, i32) -> i32
// CHECK-RESTRUCTURE-NEXT:       llvm.br ^bb6
// CHECK-RESTRUCTURE-NEXT:     ^bb5:  // pred: ^bb1
// CHECK-RESTRUCTURE-NEXT:       llvm.br ^bb2
// CHECK-RESTRUCTURE-NEXT:     ^bb6:  // 2 preds: ^bb3, ^bb4
// CHECK-RESTRUCTURE-NEXT:       %15 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:       %16 = llvm.add %15, %3  : i32
// CHECK-RESTRUCTURE-NEXT:       llvm.store %16, %9 : i32, !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:       %17 = llvm.load %10 : !llvm.ptr -> i32
// CHECK-RESTRUCTURE-NEXT:       %18 = llvm.add %17, %3  : i32
// CHECK-RESTRUCTURE-NEXT:       llvm.store %18, %10 : i32, !llvm.ptr
// CHECK-RESTRUCTURE-NEXT:       llvm.br ^bb8
// CHECK-RESTRUCTURE-NEXT:     ^bb7:  // pred: ^bb1
// CHECK-RESTRUCTURE-NEXT:       clift.goto %0 !clift.label
// CHECK-RESTRUCTURE-NEXT:     ^bb8:  // pred: ^bb6
// CHECK-RESTRUCTURE-NEXT:       "clift.continue"() : () -> ()
// CHECK-RESTRUCTURE-NEXT:     } ^bb1
// CHECK-RESTRUCTURE-NEXT:   }
// CHECK-RESTRUCTURE-COM: llvm.func @printf(!llvm.ptr, ...) -> i32 attributes {passthrough = [["frame-pointer", "all"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]}
// CHECK-RESTRUCTURE-NEXT: }

// CHECK-COMB-LABEL: module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<"dlti.endianness", "little">, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>>} {
// CHECK-COMB-NEXT:   llvm.mlir.global private unnamed_addr constant @".str"("%d\00") {addr_space = 0 : i32, alignment = 1 : i64, dso_local}
// CHECK-COMB-NEXT:   llvm.func @foo(%arg0: i32, %arg1: i32) attributes {passthrough = ["noinline", "nounwind", "optnone", ["uwtable", "2"], ["frame-pointer", "all"], ["min-legal-vector-width", "0"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]} {
// CHECK-COMB-NEXT:     %0 = clift.make_label !clift.label
// CHECK-COMB-NEXT:     %1 = clift.make_label !clift.label
// CHECK-COMB-NEXT:     %2 = clift.make_label !clift.label
// CHECK-COMB-NEXT:     %3 = llvm.mlir.constant(1 : i32) : i32
// CHECK-COMB-NEXT:     %4 = llvm.mlir.constant(10 : i32) : i32
// CHECK-COMB-NEXT:     %5 = llvm.mlir.constant(5 : i32) : i32
// CHECK-COMB-NEXT:     %6 = llvm.mlir.constant("%d\00") : !llvm.array<3 x i8>
// CHECK-COMB-NEXT:     %7 = llvm.mlir.addressof @".str" : !llvm.ptr
// CHECK-COMB-NEXT:     %8 = llvm.mlir.constant(7 : i32) : i32
// CHECK-COMB-NEXT:     %9 = llvm.alloca %3 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
// CHECK-COMB-NEXT:     %10 = llvm.alloca %3 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
// CHECK-COMB-NEXT:     llvm.store %arg0, %9 : i32, !llvm.ptr
// CHECK-COMB-NEXT:     llvm.store %arg1, %10 : i32, !llvm.ptr
// CHECK-COMB-NEXT:     llvm.br ^bb2
// CHECK-COMB-NEXT:   ^bb1:  // pred: ^bb2
// CHECK-COMB-NEXT:     clift.assign_label %0 !clift.label
// CHECK-COMB-NEXT:     llvm.return
// CHECK-COMB-NEXT:   ^bb2:  // pred: ^bb0
// CHECK-COMB-NEXT:     clift.loop {
// CHECK-COMB-NEXT:       llvm.br ^bb1
// CHECK-COMB-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-COMB-NEXT:       %11 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:       %12 = llvm.icmp "slt" %11, %4 : i32
// CHECK-COMB-NEXT:       llvm.cond_br %12, ^bb5, ^bb7
// CHECK-COMB-NEXT:     ^bb2:  // pred: ^bb5
// CHECK-COMB-NEXT:       clift.loop {
// CHECK-COMB-NEXT:         llvm.br ^bb1
// CHECK-COMB-NEXT:       ^bb1:  // pred: ^bb0
// CHECK-COMB-NEXT:         %19 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:         %20 = llvm.icmp "eq" %19, %5 : i32
// CHECK-COMB-NEXT:         llvm.cond_br %20, ^bb4, ^bb2
// CHECK-COMB-NEXT:       ^bb2:  // pred: ^bb1
// CHECK-COMB-NEXT:         %21 = llvm.load %10 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:         %22 = llvm.call @printf(%7, %21) : (!llvm.ptr, i32) -> i32
// CHECK-COMB-NEXT:         %23 = llvm.load %10 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:         %24 = llvm.icmp "eq" %23, %8 : i32
// CHECK-COMB-NEXT:         llvm.cond_br %24, ^bb3, ^bb5
// CHECK-COMB-NEXT:       ^bb3:  // pred: ^bb2
// CHECK-COMB-NEXT:         llvm.br ^bb6
// CHECK-COMB-NEXT:       ^bb4:  // pred: ^bb1
// CHECK-COMB-NEXT:         clift.goto %2 !clift.label
// CHECK-COMB-NEXT:       ^bb5:  // pred: ^bb2
// CHECK-COMB-NEXT:         clift.goto %1 !clift.label
// CHECK-COMB-NEXT:       ^bb6:  // pred: ^bb3
// CHECK-COMB-NEXT:         "clift.continue"() : () -> ()
// CHECK-COMB-NEXT:       } ^bb9, ^bb10
// CHECK-COMB-NEXT:     ^bb3:  // pred: ^bb10
// CHECK-COMB-NEXT:       clift.assign_label %1 !clift.label
// CHECK-COMB-NEXT:       llvm.br ^bb6
// CHECK-COMB-NEXT:     ^bb4:  // pred: ^bb9
// CHECK-COMB-NEXT:       clift.assign_label %2 !clift.label
// CHECK-COMB-NEXT:       %13 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:       %14 = llvm.call @printf(%7, %13) : (!llvm.ptr, i32) -> i32
// CHECK-COMB-NEXT:       llvm.br ^bb6
// CHECK-COMB-NEXT:     ^bb5:  // pred: ^bb1
// CHECK-COMB-NEXT:       llvm.br ^bb2
// CHECK-COMB-NEXT:     ^bb6:  // 2 preds: ^bb3, ^bb4
// CHECK-COMB-NEXT:       %15 = llvm.load %9 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:       %16 = llvm.add %15, %3  : i32
// CHECK-COMB-NEXT:       llvm.store %16, %9 : i32, !llvm.ptr
// CHECK-COMB-NEXT:       %17 = llvm.load %10 : !llvm.ptr -> i32
// CHECK-COMB-NEXT:       %18 = llvm.add %17, %3  : i32
// CHECK-COMB-NEXT:       llvm.store %18, %10 : i32, !llvm.ptr
// CHECK-COMB-NEXT:       llvm.br ^bb8
// CHECK-COMB-NEXT:     ^bb7:  // pred: ^bb1
// CHECK-COMB-NEXT:       clift.goto %0 !clift.label
// CHECK-COMB-NEXT:     ^bb8:  // pred: ^bb6
// CHECK-COMB-NEXT:       "clift.continue"() : () -> ()
// CHECK-COMB-NEXT:     ^bb9:  // pred: ^bb2
// CHECK-COMB-NEXT:       llvm.br ^bb4
// CHECK-COMB-NEXT:     ^bb10:  // pred: ^bb2
// CHECK-COMB-NEXT:       llvm.br ^bb3
// CHECK-COMB-NEXT:     } ^bb1
// CHECK-COMB-NEXT:   }
// CHECK-COMB-COM:   llvm.func @printf(!llvm.ptr, ...) -> i32 attributes {passthrough = [["frame-pointer", "all"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]}
// CHECK-COMB-NEXT: }
